version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: react_antd
    container_name: react_antd
    ports:
      - "8080:8080"
    networks:
      - ionnet
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  ionnet:
    external: true
    name: ionnet
